authv1: Modernize returned service catalog
Keystone has only been returning v3 catalogs for a while now, so many
client libraries have dropped support for the old v2 catalogs. We should
switch to the new format so we stop causing KeyErrors like

    File ".../cliff/formatters/table.py", line 109, in add_rows
      table.add_row(_format_row(first_row))
                    ^^^^^^^^^^^^^^^^^^^^^^
    File ".../cliff/formatters/table.py", line 38, in _format_row
      r = r.human_readable()
          ^^^^^^^^^^^^^^^^^^
    File ".../openstackclient/identity/v3/catalog.py", line 37, in human_readable
      ret += "  {}: {}\n".format(ep['interface'], ep['url'])
                                 ~~^^^^^^^^^^^^^
  KeyError: 'interface'

(Previously seen while trying to run `openstack catalog show` with latest
python-openstackclient/osc-lib/openstacksdk -- but this used to work!)

Change-Id: Ie8726b97e1dde7d7bfd8e4215af6af52e1fd870e
Signed-off-by: Tim Burke <tim.burke@gmail.com>